### PR TITLE
function update_scripts - Begining of self update

### PR DESCRIPTION
**Pull request by ColdShadow80**
function update_scripts(){
	echo "updating myself..."

use -s parameter to call  update_scripts function.
(Implementation of self update for update_mad.sh)

### CODE REVIEW

**Comment by krzee** [comment]
very interesting idea, im thinking we could have -s get passed to update_mad to update the init stuff, and if we need to update update_mad we can add those updates to the init script.

I like this!

im not sure a script can overwrite itself while its running, but the above solution would get around that.

**Comment by ColdShadow80** [comment]
That is the idea.
Update itself so it can be used to update all ATVs scripts.
If something needs correcting or a new file is created update_mad.sh can be updated and after that it could update all others.

**Comment by krzee** [comment]
i did not think of this until your PR, but im thinking update_mad.sh updates the 16mad init script. and if there are actual updates to update_mad itself, we add that directly to the init script. so no file needs to attempt to update itself in place while executing.

This would made updating the init script optional, which is probably good. and it could easily be done via madmin job.

**Comment by ColdShadow80** [comment]
Yes, the point was to get a working base to 2 things:
1. I was getting tired of uploading updates to this script manually.
2. Alternative fix to "https://github.com/Map-A-Droid/MAD-ATV/issues/16" and a way to keep boxes updated by MAD jobs without reflashing.

**Comment by krzee** [comment]
i love it! so can you change the PR to have update_mad update init instead of itself?
I'm pretty sure that otherwise in testing youd find that you cant have a script update itself while its running

**Comment by krzee** [comment]
then in the init script we can just grep the current version of update_mad and if its not latest version then we update it

then to get into latest version we could release a madmin job to get the init script and next boot it'll update update_mad and be on latest version

**Comment by krzee** [comment]
this had conflicts and touched a readme file that already had been updated. but it was a great idea so i merged it in by hand. thank you!

**Pull request closed without merging**
