### PR TITLE
not need uninstall for upgrade package

### PR DESCRIPTION
**Pull request by korentzari**

### CODE REVIEW

**Comment by muckelba** [comment]
Try to downgrade Pogo via adb. That won't work apparently. You need to uninstall it first

**Comment by JimBim89** [comment]
So also add -d for downgrade?

**Comment by hartlomiej** [comment]
It should say `adb install -rd pathtoapk/game.apk`

**Comment by muckelba** [comment]
Didn't know about that parameter until now. But if that works, sure

**Comment by cyphercris** [comment]
Can edit question and add command to install apks too? Google Play shop don't work well at atv with mad ROM, so all should be install by apk

**Comment by krzee** [comment]
Is this actually a FAQ?
I would expect every time this happens the answer would be: update your addresses.json

Mad usually supports the latest apk in addresses.json within minutes of it going up on apkmirror, last game update our addresses.json was updated 2 minutes BEFORE we got the apkmirror announcement from the bot.

**Pull request merged**
