### PR TITLE
Update README_autoconfig.md

### PR DESCRIPTION
**Pull request by TechG3n**

### CODE REVIEW

**Review by krzee — COMMENTED** [review]
why root directory? it can be in ANY directory on the usb

**Comment by TechG3n** [comment]
Only worked in root for me and snoopy pointed it to me

**Comment by krzee** [comment]
i literally dont use the root dir of my sdcard for my 32bit autoconfig.
the commands that find it in 32bit are:
`usbfile="$(find /mnt/media_rw/ -name com.mad.pogodroid_preferences.xml|head -n1)"`
`usbofile="$(find /mnt/media_rw/ -name madorigin.txt|head -n1)"`
`...`
`usbfile="$(find /mnt/media_rw/ -name de.grennith.rgc.remotegpscontroller_preferences.xml|head -n1)"`
it takes the first copy of those filenames that it finds anywhere on your usb stick.


and on 64bit it uses:
`
usbfile="$(find /mnt/media_rw/ -name mad_autoconf.txt|head -n1)"
`
so again it will use the first copy of that file seen ANYWHERE on the usb.

**Comment by krzee** [comment]
if you just use this:
https://github.com/Map-A-Droid/MAD-ATV/blob/master/setup_autoconfig.sh
it'll put the files in a dir named mad_autoconfig in your sd card

**Comment by TechG3n** [comment]
I have used the manual way, never seen that script :D

**Comment by krzee** [comment]
ya its kinda new, maybe youd like to test it and amend this PR to talk about using it instead?

**Comment by krzee** [comment]
have usb stick in the atv,
be in adb shell, as root:

`curl -L -o /sdcard/setup_autoconfig.sh -s -k https://raw.githubusercontent.com/Map-A-Droid/MAD-ATV/master/setup_autoconfig.sh`
`sh /sdcard/setup_autoconfig.sh`


(a job could be made to do this, but i been more focused on 64bit which is about to make this irrelevant)

**Comment by TechG3n** [comment]
Yes let me try this. You can close this one or rewrite it to use this script?
Depends on how long you think we will use it

**Comment by krzee** [comment]
hopefully mad will merge 64bit madmin parts this week, if not today... after that happens its up to people what pace they wish to update. i think 64bit is working better some will migrate faster than others... there will be some setup in madmin and also theres a small issue with adding google accounts sometimes people get a window to add a phone. we know how to fix this but it will take a little time to gather the right data and test a solution because only certain people get the problem (im not one of the people)

**Comment by krzee** [comment]
ill leave this ticket open in case you choose to change it, that way this conversation gets submitted with the merge, if you choose to say screw it, you can just close it

**Review by krzee — APPROVED** [review]
thanks for doing that

**Pull request merged**
