### PR TITLE
update 42mad

### PR DESCRIPTION
**Pull request by acocalypso**
- first repack magisk then do autoupdate
- add google account setup to install procedure

### CODE REVIEW

**Comment by acocalypso** [comment]
again my repo is screwed ...

**Comment by krzee** [comment]
> 
> 
> again my repo is screwed ...

git diff wants to be your friend :)

**Comment by krzee** [comment]
also, it says "add google account setup to install procedure"
but how would you populate that info during install before we get it from madmin? thats why the trigger currently doesnt exist yet

**Comment by krzee** [comment]
although i guess it needs to be called in the script so it can even be tested at all after the file is populated, you're right it does belong

**Comment by acocalypso** [comment]
check my new cleaned pr :D

**Pull request closed without merging**
