### PR TITLE
Add note about AMD processors

### PR DESCRIPTION
**Pull request by LegitDongo**

### CODE REVIEW

**Comment by sn0opy** [comment]
It does run on zen 2 / AMD 3000 series processors though. At least it worked like a charm on my 3900x

**Comment by Boby360** [comment]
Works fine on my 8350.

**Comment by fosJoddie** [comment]
I could not get it to work on my ryzen 5 so i guess it depends on the age of the cpu too

**Comment by Boby360** [comment]
Ryzen 5 applies to all 3 current generations I believe. Just as I3 i5 i7 isn't generation based. 

Works fine on my old fx series and works fine on 3000 series from the sounds of it. 

Are you running first Gen ryzen?

**Comment by LegitDongo** [comment]
I've got a Ryzen 1700X and had issues with it as well, I believe it's first-gen.

**Comment by fosJoddie** [comment]
Doh... yeah a 1600 here , forhot to add that

**Comment by Boby360** [comment]
So potentially all first Gen ryzen doesn't work with the app. Confirmed ryzen 5 part of 1000 series at the least.

**Comment by krzee** [comment]
sounds like you guys are getting it figured out a little, if you guys want to make an info file full of this info, i'll merge it and when more is found it can get added there

**Pull request merged**
