### PR TITLE
Update Custom Update Mad Rom - 5 minute Bash.json

### PR DESCRIPTION
**Pull request by ColdShadow80**
**Added:**
-Missing Reboot
-More user info
_-Wishfull
5m-mad-batch_V1 2
 thinking_

### CODE REVIEW

**Review by krzee — COMMENTED** [review]
```            "TYPE": "jobType.PASSTHROUGH",
            "SYNTAX": "su  -c '/system/bin/update_mad.sh -i && reboot && print EXPECT_FAULTY_RESULT_RUNNING_THIS_JOB-NOTE_PRINT_COMMAND_IS_WISHFULL_THINKING_HERE'",
```
this can work if we remove the reboot from both here AND the update_mad script, and then add another job which is jobtype.reboot to the chain

**Comment by ColdShadow80** [comment]
Ok, but... where is the reboot in the update_mad.sh script when running-i option?

**Comment by JabLuszko** [comment]
https://github.com/Map-A-Droid/MAD-ATV/blob/master/update_mad.sh#L124

if any of those 'flags'/'options' are set it will trigger reboot_device

**Comment by krzee** [comment]
i'll get that part. i want to check out the environment and only run the reboot if its being ran from CLI not from RGC.

**Comment by krzee** [comment]
update_mad.sh v2.5 is in rom 1.0.6 and will only reboot when called via sh, not when called via madmin.

**Comment by ColdShadow80** [comment]
Updated to version 1.3.1

Working with update_mad.sh version 2.5 (wich does not reboot when called from MADadmin)

5m-mad-batch_V1 3 1

**Pull request merged**
